### 환자 등록
POST http://localhost:8080/api/v1/patients
Content-Type: application/json

{
  "hospitalId": 1,
  "patientName": "김환자",
  "patientRegistrationNumber": "9988776655442",
  "genderCode": "F",
  "birthDay": "1990-05-31",
  "phoneNumber": "010-1111-2222"
}

### 환자 수정
PATCH http://localhost:8080/api/v1/patients/1
Content-Type: application/json

{
  "hospitalId": 2,
  "patientName": "김퇴원김퇴원김퇴원",
  "patientRegistrationNumber": "1234123422331",
  "genderCode": "F",
  "birthDay": "1990-05-31",
  "phoneNumber": "010-1111-9999"
}

### 환자 삭제
DELETE http://localhost:8080/api/v1/patients
Content-Type: application/json

### 환자 조회 1
GET http://localhost:8080/api/v1/patients/1
Content-Type: application/json

### 환자 조회 2
GET http://localhost:8080/api/v1/patients/2
Content-Type: application/json

### 환자 조회 페이징 및 검색
GET http://localhost:8080/api/v1/patients
Content-Type: application/json